apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - image: scheele/reverseproxy
    name: reverseproxy
    imagePullPolicy: Always       
    ports:
    - containerPort: 8080
  restartPolicy: Always
