#!/bin/bash

# check for the last tag version
# VERSION="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -1)"
VERSION=latest

# push the latest build to registry
docker push ratchadj2016/cloud-developer-my-instagram-restapi-feed:$VERSION;
docker push ratchadj2016/cloud-developer-my-instagram-restapi-user:$VERSION;
docker push ratchadj2016/cloud-developer-my-instagram-reverseproxy:$VERSION;
docker push ratchadj2016/cloud-developer-my-instagram-frontend:local;