#!/bin/bash
# check for the last tag version

# VERSION="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -1)"
VERSION=latest
echo "BUILD TAG:$VERSION"

# build with that version
docker build --rm -f "./Dockerfile" -t ratchadj2016/cloud-developer-my-instagram-restapi-feed:$VERSION .
